name: Test WARM

on: push

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    
    steps:
    - name: installing llvm
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: creating symlinks
      run: |
        sudo ln -svf /usr/bin/clang-9 /usr/bin/clang
        sudo ln -svf /usr/bin/wasm-ld-9 /usr/bin/wasm-ld
        sudo ln -svf /usr/bin/llc-9 /usr/bin/llc
        sudo ln -svf /usr/bin/llvm-nm-9 /usr/bin/llvm-nm
        sudo ln -svf /usr/bin/llvm-ar-9 /usr/bin/llvm-ar
    - name: building wasi-libc
      run: |
        git clone https://github.com/WebAssembly/wasi-libc.git
        cd wasi-libc
        make WASM_CC=/usr/bin/clang WASM_AR=/usr/bin/llvm-ar WASM_NM=/usr/bin/llvm-nm
    - name: running script
      run: |
        git clone https://github.com/cryptid-org/warm.git
        cd warm/
        ./make.sh clang "--sysroot=/home/runner/work/warm/warm/wasi-libc/sysroot -O2 -flto" llvm-ar
